-- 用户登录次数表[20170901, 20180131]
CREATE TABLE test.TBL_LOGIN_TIMES_20170901_20180131 (
  USER_ID BIGINT PRIMARY KEY,
  LOGIN_TIMES INT DEFAULT 0 COMMENT '登录次数'
);

-- 每日登录人数、人次统计
CREATE TABLE TBL_DAU (
  DATE CHAR(10) NOT NULL COMMENT '日期',
  TYPE CHAR(4) NOT NULL COMMENT '平台',
  USERS INT DEFAULT 0 COMMENT '登录人数',
  COUNT INT DEFAULT 0 COMMENT '登录次数'
);

-- 用户注册省份分布(按认证学校计算)
DROP TABLE IF EXISTS TBL_USER_AREAL ;
CREATE TABLE TBL_USER_AREAL (
  PROVINCE VARCHAR(128) COMMENT '省份' ,
  USERS INT DEFAULT 0 COMMENT '人数',
  DATE DATE NOT NULL COMMENT '统计日期',
  PRIMARY KEY (PROVINCE, DATE)
);

-- 用户角色注册人数
DROP TABLE IF EXISTS TBL_USER_ROLE ;
CREATE TABLE TBL_USER_ROLE (
  ROLE TINYINT COMMENT '角色：1学生、2教师' ,
  USERS INT DEFAULT 0 COMMENT '人数',
  DATE DATE NOT NULL COMMENT '统计日期',
  PRIMARY KEY (ROLE, DATE)
);